services:
  srsran_ue_host:
    image: ghcr.io/sulaimanalmani/srsranzmq/srsue:v1.1
    container_name: srsran_ue_host2
    privileged: true
    networks:
      ue_net:
        ipv4_address: 10.54.1.235
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_ADMIN
      - IPC_LOCK
    volumes:
      - ./config:/srsran/config
    env_file:
      - .env
    command: >
      /bin/bash -c "
      chmod +x /srsran/config/*.sh &&
      /srsran/config/wrapper.sh"

  ue_metrics_agent:
    image: prom/node-exporter:latest

networks:
  ue_net:
    name: ue-net
    external: true