
services:
  telegraf:
    container_name: telegraf
    image: srsran/telegraf
    build:
      context: telegraf
    # Removed depends_on: influxdb constraint
    env_file:
      - .env.external-influxdb
    # volumes:
    #   - /tmp/metrics.txt:/etc/srs/metrics.txt:ro
    networks:
      metrics:
        ipv4_address: 172.19.1.4

  grafana:
    container_name: grafana
    image: srsran/grafana
    build:
      context: grafana
      args:
        GF_VERSION: ${GF_VERSION}
        LOGO_URL: ${GF_LOGO_URL}
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    env_file:
      - .env.external-influxdb
    depends_on:
      telegraf:
        condition: service_started
    ports:
      - 3300:${GF_PORT}
    networks:
      metrics:
        ipv4_address: 172.19.1.6

volumes:
  grafana-storage:
# Removed influxdb-storage volume

networks:
  metrics:
    external: true