services:
  srsran_ue_host:
    image: ghcr.io/sulaimanalmani/srsranzmq/srsue:v1.1
    container_name: srsran_ue_host
    privileged: true
    networks:
      external_n3:
        ipv4_address: 10.10.3.234
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - IPC_LOCK
    volumes:
      - ./config:/srsran/config
    environment:
      - DEBUG_MODE=false
      # These IPs are now reachable via the route we added to the host
      - GNB_IP=10.10.3.231
      - ZMQ_BRIDGE_IP=10.10.3.236
      - UE_ZMQ_MODE=bridge
      - UE_DNS1=1.1.1.1
      - UE_DNS2=8.8.8.8
    command: >
      /bin/bash -c "
      chmod +x /srsran/config/*.sh &&
      /srsran/config/wrapper.sh"

  ue_metrics_agent:
    image: prom/node-exporter:latest

networks:
  external_n3:
    external: true
    name: ue_n3