services:
  srsue:
    image: ghcr.io/sulaimanalmani/srsranzmq/srsue:v1.1
    container_name: srsran_srsue
    networks:
      n3:
        ipv4_address: 10.10.3.232
    environment:
      - GNB_TX_HOST=${GNB_TX_HOST:-10.53.1.3}
      - GNB_TX_PORT=${GNB_TX_PORT:-2000}
      - GNB_RX_HOST=${GNB_RX_HOST:-10.53.1.6}
      - GNB_RX_PORT=${GNB_RX_PORT:-2001}
      - OPEN5GS_AMF=${OPEN5GS_AMF:-10.53.1.2}
      - UE_IMSI=${UE_IMSI:-001010000000002}
      - UE_ID=${UE_ID:-0}
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - SYS_ADMIN
      - IPC_LOCK
    privileged: true
    volumes:
      - ./config:/srsran/config
    tmpfs:
      - /tmp
    command: >
      /bin/bash -c "
      chmod +x /srsran/config/*.sh &&
      /srsran/config/wrapper.sh"

networks:
  n3:
    external: true
